# Generated by Django 5.1.7 on 2025-03-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=255)),
                ('r_description', models.TextField()),
                ('r_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
