# Generated by Django 5.1.7 on 2025-03-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_remove_student_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
